In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

arr[0] = 99
arr[-1] = 456

print(arr)

last_four = arr[-4:]

print(last_four)

last_four[0] = 700

print(arr)

[ 99   2   3   4   5   6   7   8   9 456]
[  7   8   9 456]
[ 99   2   3   4   5   6 700   8   9 456]


In [9]:
l = [99, 2, 3, 4, 5, 6, 7, 8, 9, 456]
l_copy = l[:]

print(l[:])

[99, 2, 3, 4, 5, 6, 7, 8, 9, 456]
