In [10]:
import numpy as np

print(np.zeros(10))
print(np.ones(10))
print(np.empty(10))

print(np.arange(1, 10, 2))
print(np.linspace(100, 200, num = 7))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 3 5 7 9]
[100.         116.66666667 133.33333333 150.         166.66666667
 183.33333333 200.        ]
