In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [5]:
row_targets = iris.target_names[iris.target]

In [6]:
setosas, versicolors, virginicas = ([iris.data[row_targets == x] for x in iris.target_names])

In [11]:
print(np.mean(setosas, axis = 0))
print(np.median(setosas, axis = 0))
print(np.std(setosas, axis = 0))
print(np.var(setosas, axis = 0))
print(np.min(setosas, axis = 0))
print(np.max(setosas, axis = 0))

[5.006 3.428 1.462 0.246]
[5.  3.4 1.5 0.2]
[0.34894699 0.37525458 0.17191859 0.10432641]
[0.121764 0.140816 0.029556 0.010884]
[4.3 2.3 1.  0.1]
[5.8 4.4 1.9 0.6]


In [15]:
print(np.mean(setosas, axis = 0))
print(np.mean(versicolors, axis = 0))
print(np.mean(virginicas, axis = 0))
print()
print(np.median(setosas, axis = 0))
print(np.median(versicolors, axis = 0))
print(np.median(virginicas, axis = 0))
print()
print(np.std(setosas, axis = 0))
print(np.std(versicolors, axis = 0))
print(np.std(virginicas, axis = 0))

[5.006 3.428 1.462 0.246]
[5.936 2.77  4.26  1.326]
[6.588 2.974 5.552 2.026]

[5.  3.4 1.5 0.2]
[5.9  2.8  4.35 1.3 ]
[6.5  3.   5.55 2.  ]

[0.34894699 0.37525458 0.17191859 0.10432641]
[0.51098337 0.31064449 0.46518813 0.19576517]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [21]:
descriptive_stats = np.array([
    [
        np.mean(setosas, axis = 0),
        np.mean(versicolors, axis = 0),
        np.mean(virginicas, axis = 0),
    ],
    [
        np.std(setosas, axis = 0),
        np.std(versicolors, axis = 0),
        np.std(virginicas, axis = 0),
    ]
])

In [22]:
print(descriptive_stats)

[[[5.006      3.428      1.462      0.246     ]
  [5.936      2.77       4.26       1.326     ]
  [6.588      2.974      5.552      2.026     ]]

 [[0.34894699 0.37525458 0.17191859 0.10432641]
  [0.51098337 0.31064449 0.46518813 0.19576517]
  [0.62948868 0.31925538 0.54634787 0.27188968]]]
