In [2]:
import numpy as np

In [12]:
# 1
arr = np.arange(0, 25)
print(arr[arr > 5][[0, 1, -2, -1]])

#2 
first_half = arr[np.arange(0, arr.size // 2)]
print(first_half[first_half > 5])

#3
arr_extend = arr.reshape((5, 5))
arr_extend[np.sum(arr_extend, axis = 1) > 20][:, [0, -1]]

[ 6  7 23 24]
[ 6  7  8  9 10 11]


array([[ 5,  9],
       [10, 14],
       [15, 19],
       [20, 24]])