In [1]:
import numpy as np

In [4]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[0])
print(array_1d[-1])
print(array_1d[:3])

1
5
[1 2 3]


In [20]:
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list_3d = [list_2d[:], [[x + 9 for x in row] for row in list_2d], [[x + 18 for x in row] for row in list_2d]]

array_2d = np.array(list_2d)
array_3d = np.array(list_3d)

# print(array_2d[0, 0])

print(array_3d)
print(array_3d[-1, -1, 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
25
