In [2]:
import numpy as np

list_3d = [
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ],
    [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
    ]
]

array_3d = np.array(list_3d)
array_4d = np.array([array_3d, array_3d + 27, array_3d + 54])
print(array_4d)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]
   [61 62 63]]

  [[64 65 66]
   [67 68 69]
   [70 71 72]]

  [[73 74 75]
   [76 77 78]
   [79 80 81]]]]


In [6]:
print(array_4d[0, 1, 1, -1])
print(array_4d[1, 0, 0, 1])
print(array_4d[1, 1, 1])
print(array_4d[-1, :2, :2])

15
29
[40 41 42]
[[[55 56 57]
  [58 59 60]]

 [[64 65 66]
  [67 68 69]]]
