In [1]:
import numpy as np

In [20]:
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
list_3d = [list_2d[:], list_2d[:], list_2d[:]]
# list_3d[0][1][0] = 100

print(list_2d)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [21]:
array_2d = np.array(list_2d)
array_3d = np.array(list_3d)
array_3d[1, 1, 1] = 100

# print(array_2d)
print(array_3d)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[  1   2   3]
  [  4 100   6]
  [  7   8   9]]

 [[  1   2   3]
  [  4   5   6]
  [  7   8   9]]]
