In [1]:
import numpy as np

In [21]:
arr_1d = np.array([67, 23, 10, -100, 234, 5])
str_arr_1d = np.array(['cherry', 'banana', 'date', 'apple', 'eggplant'])
# arr_1d.sort() # Sorted Original Data
# str_arr_1d.sort()

arr_1d_sorted = np.sort(arr_1d)
sorted_str_arr_1d = np.sort(str_arr_1d)

sorted_indecies = np.argsort(arr_1d)

In [23]:
print(arr_1d)
print(arr_1d_sorted)

print(str_arr_1d)
print(sorted_str_arr_1d)

print(sorted_indecies)

for i in sorted_indecies:
    print(arr_1d[i])

[  67   23   10 -100  234    5]
[-100    5   10   23   67  234]
['cherry' 'banana' 'date' 'apple' 'eggplant']
['apple' 'banana' 'cherry' 'date' 'eggplant']
[3 5 2 1 0 4]
-100
5
10
23
67
234
