In [1]:
import numpy as np

In [5]:
my_arr = np.array([1, 2, 3, 4])
print(my_arr + 1)
print(my_arr > 2)
print(my_arr ** 2)

[2 3 4 5]
[False False  True  True]
[ 1  4  9 16]


In [3]:
def plus_one(x):
    return x + 1

list(map(plus_one, [1, 2, 3, 4]))

[2, 3, 4, 5]

In [10]:
my_arr2 = np.array([100, 200, 300, 400])

print(my_arr + my_arr2)
print(my_arr > my_arr2)
print(my_arr2 ** my_arr)

[101 202 303 404]
[False False False False]
[        100       40000    27000000 25600000000]
