In [1]:
import numpy as np

In [6]:
my_arr_2d = np.arange(0, 16).reshape((4, 4))
print(my_arr_2d)

print()

my_arr_2d_2d = np.arange(0, 160, 10).reshape((4, 4))
print(my_arr_2d_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]


In [8]:
my_arr_2d - my_arr_2d_2d

array([[   0,   -9,  -18,  -27],
       [ -36,  -45,  -54,  -63],
       [ -72,  -81,  -90,  -99],
       [-108, -117, -126, -135]])

In [10]:
my_arr_2d = np.arange(0, 16).reshape((4, 4))
print(my_arr_2d)

print()

my_arr_2d_2d = np.arange(0, 80, 10).reshape((2, 4))
print(my_arr_2d_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0 10 20 30]
 [40 50 60 70]]


In [15]:
three_by_one = np.array([1, 2, 3])
one_by_four = np.array([[1], [2], [3], [4]])

three_by_one + one_by_four

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [19]:
top = np.arange(1, 13)
side = np.arange(1, 13).reshape(-1, 1)

top * side

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])